[phases.setup]
aptPkgs = ["libpq-dev", "libcairo2-dev", "pkg-config", "python3-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn perfumeria.wsgi --workers 2 --threads 2 --timeout 120 --log-file -"
