# Generated by Django 4.2.23 on 2025-11-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('wawallet', 'WaWallet'), ('transferencia', 'Transferencia Bancaria')], default='efectivo', max_length=50),
        ),
    ]
