# Generated by Django 4.2.23 on 2025-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_api', '0004_alter_detallefactura_options_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'Verificación de Email',
                'verbose_name_plural': 'Verificaciones de Email',
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
