# Generated by Django 4.2.23 on 2025-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_api', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuento_aplicado',
            field=models.BooleanField(default=False, help_text='Indica si se aplicó el descuento del 15% por compras mayores a $500', verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en dólares descontada (15% del subtotal)', max_digits=10, verbose_name='Monto de descuento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_sin_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio original antes de aplicar el descuento del 15%', max_digits=10, verbose_name='Total sin descuento'),
        ),
    ]
